#!/bin/bash

#SBATCH --nodes=1 
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4         
#SBATCH --mem=60G                   
#SBATCH --time=05:00:00             
#SBATCH -J c_driver.c
#SBATCH -p long                 
#SBATCH -o /data/mfulghieri/mesmer/outputs/c_driver/c_driver_test.out
#SBATCH -e /data/mfulghieri/mesmer/outputs/c_driver/c_driver_test.err


source $(conda info --base)/etc/profile.d/conda.sh
conda activate mesmer

module load gcc-11.3.0/ompi-4.1.4_nccl
module load cmake-3.22.1

cd /data/mfulghieri/mesmer/

DIR="exe"
EXE="mesmer_from_c"
INPUT="myworksite/inputs/first_test"

mkdir -p "${DIR}"

# gcc c_driver.c runs the C-model simple file c_driver.c
# -L. to search in cwd the libraries (.a)
# include the static library libmesmerfull.a generated by the make
# -lm: links the system's standard math library (required for functions such as sin, cos, exp)
# -lgfortran: links the Fortran runtime, because the MESMER library is written in Fortran
# -o mesmer_from_c: defines the name of the final executable binary file to be generated
gcc c_driver.c -L. -lmesmerfull -lm -lgfortran -o "${DIR}"/"${EXE}" 

echo "Executable create in "${DIR}"/"${EXE}""


# Run the new-generated executable
./"${DIR}"/"${EXE}" "${INPUT}"

echo "All done!"

